%general graphics, this will apply to any figure you open
%(groot is the default figure object).

%set(groot, ...
%'DefaultFigureColor', 'w', ...
%'DefaultAxesLineWidth', 0.5, ...
% 'DefaultAxesXColor', 'k', ...
% 'DefaultAxesYColor', 'k', ...
% 'DefaultAxesFontUnits', 'points', ...
% 'DefaultAxesFontSize', 8, ...
% 'DefaultAxesFontName', 'Helvetica', ...
% 'DefaultLineLineWidth', 1, ...
% 'DefaultTextFontUnits', 'Points', ...
% 'DefaultTextFontSize', 8, ...
% 'DefaultTextFontName', 'Helvetica', ...
% 'DefaultAxesBox', 'off', ...
% 'DefaultAxesTickLength', [0.02 0.025]);
 
% set the tickdirs to go out - need this specific order
% set(groot, 'DefaultAxesTickDir', 'out');
% set(groot, 'DefaultAxesTickDirMode', 'manual');
x = 1:3
plot(x)